#---------------------------->> Credentials <<----------------------------#
#                   Replace these values with your tokens                 #
#           !IMPORTANT! - Do not share these values with anyone!          #
#-------------------------------------------------------------------------#

# Discord Bot Token
# Get it on https://discord.com/developers/applications/
DISCORD_TOKEN: "ODk4MjY3NDAxNjY4NDA3Mzc3.Gn-pGQ.XQ1ucUDBAy3R1wLsW7WF8gq9w-UyxNu8odJVME"

# MariaDB SQL Token
# This Key is privat. Replace it with your own SQL Key
SQL_TOKEN: "GutesPasswort"


TWITCH_TOKEN: "f9iqnaxobzgok4mfj8sgrxbk1sebzb"
