#---------------------------->> Credentials <<----------------------------#
#                   Replace these values with your tokens                 #
#           !IMPORTANT! - Do not share these values with anyone!          #
#-------------------------------------------------------------------------#

# Discord Bot Token
# Get it on https://discord.com/developers/applications/
DISCORD_TOKEN: "ODk4MjY3NDAxNjY4NDA3Mzc3.Gixc5y.JnACg5A9aV7xVSkZD_-J_ns_ea6XF0hQYSYXC4"

# MariaDB SQL Token
# This Key is privat. Replace it with your own SQL Key
SQL_TOKEN: "GutesPasswort"


TWITCH_TOKEN: "f9iqnaxobzgok4mfj8sgrxbk1sebzb"
